language: node_js
node_js:
 - 10
 - node
env:
  - CXX=g++-4.9
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.9

before_script:
  - npm run build

cache:
  apt: true
